### PR TITLE
Update dependencies 

### PR DESCRIPTION
**Pull request by thibautsabot**
using JSDOM > 10

### CODE REVIEW

**Comment by pedrotcaraujo** [comment]
It's an important change. @rstacruz can you merge it? Thanks @GinjiBan \o/

**Comment by kapouer** [comment]
Also using it, please merge this PR.

**Comment by aschonfeld** [comment]
I'm using jsdom > 10 as well, merging this PR would be a big help

**Review by sahalsaad — APPROVED** [review]

**Review by joestump — APPROVED** [review]
👍

**Review by bbrzoska — APPROVED** [review]

**Comment by rstacruz** [comment]
huge change! releasing this as 3.0.

**Pull request merged**
