### PR TITLE
pass the options to jsdom

### PR DESCRIPTION
**Pull request by kenjiru**
Pass the `options` to `jsdom.jsdom()` and offer the user the possibility to customize the `html` string.
I've also added a `jshint` config file (the default one) and cleaned the code.

This should fix issue #3.

### CODE REVIEW

**Comment by rstacruz** [comment]
This project uses standardjs.com rules, and this PR completely changes the coding style. Sorry :\

**Comment by rstacruz** [comment]
If you like, you can start over but please do leave the [coding style](http://standardjs.com/rules.html) intact!

**Comment by kenjiru** [comment]
Sorry, I didn't notice the standardjs, I haven't heard of it before.

Let me give it another try, without changing the coding styles.

**Comment by rstacruz** [comment]
yeah, totally forgot the linter there, apologies.

**Pull request closed without merging**
