### PR TITLE
Use the dom keys provided by jsdom

### PR DESCRIPTION
**Pull request by amsul**
Adds support for jsdom v9.4.0

Fixes https://github.com/rstacruz/jsdom-global/issues/6

### CODE REVIEW

**Comment by rstacruz** [comment]
Neat. How far back does that jsdom file go? Will it work with jsdom 9.0.0?

**Comment by amsul** [comment]
@rstacruz yep! Seems like it's there: https://github.com/tmpvar/jsdom/blob/f2f22937ade86225fc65177975c1ce1bfacf347b/lib/jsdom/living/index.js

**Comment by domenic** [comment]
Please do not do this. This relies on internal APIs and can break any time (and will probably break very soon). It also omits anything added in `Window.js`, like `Image`, `Audio`, `XMLHttpRequest`, and many more.

**Comment by rstacruz** [comment]
I'm inclined to side with that opinion. Mucking about internal API's is
rather unsafe.

**Comment by amsul** [comment]
@rstacruz @domenic that is definitely true. Although, it's no less fragile than the way it currently operates (as jsdom has clearly changed that functionality which was never intended to work).

And @rstacruz, even with your suggestion of a hard-coded list of keys, it's cumbersome to maintain that as time goes on.

It seems as though jsdom-global (as it is currently architected) would essentially be obsolete using just the public API of jsdom: https://github.com/tmpvar/jsdom/issues/1549#issuecomment-230213614

Instead, a testing library would need to get built that injects the scripts into jsdom, which in turn runs the tests. I briefly attempted this last night but couldn't get it working, so figured this is a decent temporary solution until we can come up with a more "proper" way to do this.

**Comment by dijs** [comment]
Ahh, this is so frustrating... I keep seeing [don't do this, and don't do that](https://github.com/tmpvar/jsdom/wiki/Don't-stuff-jsdom-globals-onto-the-Node-global). What is the **proper** way to use jsdom in tests?

@domenic If polluting the global scope with `window` properties is bad practice, does that mean this library will be useless now? And secondly, will we be forced to rewrite all of our existing tests to provide the `window` variable?

**Comment by rstacruz** [comment]
Haha, according to those docs, jsdom-global is not the recommended way to
use jsdom. Their recommendation is pretty difficult though: you'll need to
export your frontend JavaScript into a single bundle and load that to
jsdom. Quite frustrating, if you ask me.

**Comment by rstacruz** [comment]
I wouldn't call this useless though--think of it more as an unauthorized
hack ;)

**Comment by domenic** [comment]
If you can't afford to use the word "window" in your tests, then an alternative is to load up your tests into jsdom. Again, just treat jsdom like a browser, and load your tests into jsdom just like you would into a browser.

**Comment by dijs** [comment]
@domenic What do you mean by "load up your tests into jsdom". Do you have an example of this?

**Comment by domenic** [comment]
It's fairly app and test-framework specific. How would you run your tests in a browser? Just do that, pointing jsdom to the result. For example, all of the web platform tests jsdom itself uses to verify correctness are run this way, using jsdom.env plus the HTML files full of tests (which use script tags to include the test framework).

**Comment by amsul** [comment]
@domenic that means you have to bundle your package and set up sourcemaps, etc etc. This adds significant friction for enabling something very basic imo. Although I do understand why, there should still be a nicer way to achieve this without the need for bundling stuff up.

**Comment by ericclemmons** [comment]
**EDIT: I was wrong.  I was on a different branch with the old version :D**

Just spent a good chunk of time trying to debug our webpack-built tests against Enzyme + jsdom to find this thread.

The latest code in the Enzyme docs work well for me:

> http://airbnb.io/enzyme/docs/guides/jsdom.html

``` js
/* setup.js */

var jsdom = require('jsdom').jsdom;

var exposedProperties = ['window', 'navigator', 'document'];

global.document = jsdom('');
global.window = document.defaultView;
Object.keys(document.defaultView).forEach((property) => {
  if (typeof global[property] === 'undefined') {
    exposedProperties.push(property);
    global[property] = document.defaultView[property];
  }
});

global.navigator = {
  userAgent: 'node.js'
};
```

Dunno if that's what this PR should be, or maybe someone else struggling with this swap out `jsdom-global` for this instead.

(Or,  make a `enzyme-jsdom` package that reflects the docs)

👋 That's it :)

**Comment by rstacruz** [comment]
Thanks, but in the interest of not using internal API's, I'd say this should be implemented as hard-coded keys. Also, `jsdom/lib/jsdom/living` doesn't include things like `document`, `location`, `history` etc.

**Comment by rstacruz** [comment]
jsdom-global 2.1.0 is out and has this fix. Cheers! Thanks for all your help. 💕

**Pull request closed without merging**
